// Texture definitions generated by SLADE3
// on Fri Oct 12 00:17:09 2018

Sprite "YMEDA0", 28, 19
{
	Offset 13, 19
	Patch "MEDIA0", 0, 0
}

Sprite "RMEDA0", 28, 19
{
	Offset 13, 19
	Patch "MEDIA0", 0, 0
}

Sprite "YMEDI0", 28, 19
{
	Offset -3, -5
	Patch "MEDIA0", 0, 0
}

Sprite "RMEDI0", 28, 19
{
	Offset -3, -5
	Patch "MEDIA0", 0, 0
}

Sprite "SMOKA0", 100, 100
{
	XScale 2.000
	YScale 2.000
	Offset 50, 50
	Patch "PSMOKA0", 0, 0
}

Sprite "BALLA0", 55, 20
{
	XScale 2.000
	YScale 2.000
	Offset 27, 20
	Patch "DPR1H0", 0, 0
}

Sprite "STKEYS9", 7, 5
{
	Offset 0, -1
	Patch "STKEYS2", 0, 0
}

Sprite "EXITA0", 64, 64
{
	Offset 32, 64
	Patch "DPR1G0", 0, 0
}

// End of texture definitions
