// Texture definitions generated by SLADE3
// on Wed Oct 10 15:20:20 2018

Sprite "DRTBA0", 99, 53
{
	XScale 2.000
	YScale 2.000
	Offset 49, 53
	Patch "PDRTBA0", 0, 0
}

Sprite "SCIEA0", 61, 109
{
	XScale 2.000
	YScale 2.000
	Offset 30, 105
	Patch "PSCIEA0", 0, 0
}

Sprite "CIV0A0", 66, 105
{
	XScale 2.000
	YScale 2.000
	Offset 33, 101
	Patch "PCIV0A0", 0, 0
}

Sprite "YMEDA0", 28, 19
{
	Offset 13, 19
	Patch "MEDIA0", 0, 0
	{
	}
}

Sprite "RMEDA0", 28, 19
{
	Offset 13, 19
	Patch "MEDIA0", 0, 0
	{
	}
}

Sprite "YMEDI0", 28, 19
{
	Offset -3, -5
	Patch "MEDIA0", 0, 0
	{
	}
}

Sprite "RMEDI0", 28, 19
{
	Offset -3, -5
	Patch "MEDIA0", 0, 0
	{
	}
}

Sprite "FEXTI0", 45, 58
{
	XScale 2.000
	YScale 2.000
	Offset 22, 54
	Patch "PFEXTI0", 0, 0
}

Sprite "COINA0", 73, 30
{
	XScale 2.500
	YScale 2.500
	Offset 36, 31
	Patch "PCOINA0", 0, 0
}

Sprite "SMOKA0", 100, 100
{
	XScale 2.000
	YScale 2.000
	Offset 50, 50
	Patch "PSMOKA0", 0, 0
}

Sprite "BALLA0", 55, 20
{
	XScale 2.000
	YScale 2.000
	Offset 27, 20
	Patch "DPR1H0", 0, 0
}

Sprite "STKEYS9", 7, 5
{
	Offset 0, -1
	Patch "STKEYS2", 0, 0
	{
	}
}

Sprite "EXITA0", 64, 64
{
	Offset 32, 64
	Patch "DPR1G0", 0, 0
}

// End of texture definitions
