/**
 * Copyright (c) 2017-2018 DRRP-Team
 * 
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

// Texture definitions generated by SLADE3
// on Tue Oct 30 15:40:13 2018

Sprite "YMEDA0", 28, 19 {
    Offset 13, 19
    Patch "MEDIA0", 0, 0 {
        Translation "168:185=229:229", "186:191=163:163"
    }
}

Sprite "RMEDA0", 28, 19 {
    Offset 13, 19
    Patch "MEDIA0", 0, 0 {
        Translation "168:185=229:229", "80:111=168:191", "3:3=184:184", "186:191=163:163"
    }
}

Sprite "YMEDI0", 28, 19 {
    Offset -3, -5
    Patch "MEDIA0", 0, 0 {
        Translation "168:185=229:229", "186:191=163:163"
    }
}

Sprite "RMEDI0", 28, 19 {
    Offset -3, -5
    Patch "MEDIA0", 0, 0 {
        Translation "168:185=229:229", "80:111=168:191", "3:3=184:184", "186:191=163:163"
    }
}

Sprite "SMOKA0", 100, 100 {
    XScale 2.000
    YScale 2.000
    Offset 50, 50
    Patch "PSMOKA0", 0, 0
}

Sprite "BALLA0", 55, 20 {
    XScale 2.000
    YScale 2.000
    Offset 27, 20
    Patch "DPR1H0", 0, 0
}

Sprite "STKEYS9", 7, 5 {
    Offset 0, -1
    Patch "STKEYS2", 0, 0 {
        Translation "168:191=112:127", "16:47=112:127", "1:2=126:127"
    }
}

Sprite "EXITA0", 64, 64 {
    Offset 32, 64
    Patch "DPR1G0", 0, 0
}

Sprite "ALARA0", 16, 16 {
    XScale 2.000
    YScale 2.000
    Offset 8, 32
    Patch "PALARA0", 0, 0
}

Sprite "ALARB0", 16, 16 {
    XScale 2.000
    YScale 2.000
    Offset 8, 32
    Patch "PALARB0", 0, 0
}

Sprite "ALARC0", 16, 16 {
    XScale 2.000
    YScale 2.000
    Offset 8, 32
    Patch "PALARC0", 0, 0
}

Sprite "ALARD0", 16, 16 {
    XScale 2.000
    YScale 2.000
    Offset 8, 32
    Patch "PALARD0", 0, 0
}

// End of texture definitions
