/**
 *Copyright (c) 2018-2019 DRRP-Team
 *
 *This software is released under the MIT License.
 *https://opensource.org/licenses/MIT
 */


class PlayerInputHandler: EventHandler {

    override bool InputProcess( InputEvent e ) {
        if ( e.Type == e.Type_KeyDown ) DRRPUtil.ACS_NamedExecute("onInput", e.KeyChar);
        return false;
    } // of override bool InputProcess( InputEvent e ) {}

} // of class PlayerInputHandler : EventHandler {}

