
case 0:
	print(s:"Junction");
break;

case 1:
	print(s:"West wing");
break;

case 2:
	print(s:"Central corridor");
break;

case 3:
	print(s:"East wing");
break;

case 4:
	print(s:"North wing");
break;

case 5:
	print(s:"Junction");
break;

case 6:
	print(s:"/junction.bsp");
break;

case 7:
	print(s:"/level01.bsp");
break;

case 8:
	print(s:"/level02.bsp");
break;

case 9:
	print(s:"/level03.bsp");
break;

case 10:
	print(s:"/level04.bsp");
break;

case 11:
	print(s:"/level05.bsp");
break;

case 12:
	print(s:"/level06.bsp");
break;

case 13:
	print(s:"/level07.bsp");
break;

case 14:
	print(s:"Sector 1");
break;

case 15:
	print(s:"");
break;

case 16:
	print(s:"Sector 2");
break;

case 17:
	print(s:"Sector 3");
break;

case 18:
	print(s:"Sector 4");
break;

case 19:
	print(s:"Sector 5");
break;

case 20:
	print(s:"Sector 6");
break;

case 21:
	print(s:"Sector 7");
break;

case 22:
	print(s:"Welcome to Junction, Marine. Most of the people that survived the attack have regrouped here.");
break;

case 23:
	print(s:"Dr. Jensen got canned due to some security issues. I'm not sure what that was all about.");
break;

case 24:
	print(s:"I used to work with Mr. Nadira in bioresearch. He was a nice guy, until he started working with Dr. Guerard.");
break;

case 25:
	print(s:"We're screwed. It is only a matter of time before the monsters enter Junction.");
break;

case 26:
	print(s:"Junction is an area that interconnects the different areas of the base. The corridors and doors in Junction lead to all the major sectors within this facility. Some passages in Junction are locked and require highlevel security clearance to enter.");
break;

case 27:
	print(s:"You be careful.");
break;

case 28:
	print(s:"Ever heard of Kronos? Never met him but logs show he has extremely high security clearance.");
break;

case 29:
	print(s:"Hold me!");
break;

case 30:
	print(s:"You can acquire supplies and medical treatment here. Inquire with the north wing staff for more information.");
break;

case 31:
	print(s:"This door leads to the reactor powering this facility. Top-level security clearance is required to enter this area.");
break;

case 32:
	print(s:"It's my duty to guard this post. Orders from UAC HQ.");
break;

case 33:
	print(s:"I can't let you in without proper credentials.");
break;

case 34:
	print(s:"Sorry, under orders. No go without proper clearance.");
break;

case 35:
	print(s:"No.");
break;

case 36:
	print(s:"You really want in? How about we make a deal? Got 100 UAC credits?");
break;

case 37:
	print(s:"No deal. Changed my mind. Get the red keycard if you want in.");
break;

case 38:
	print(s:"Use the computer to the left to purchase supplies.");
break;

case 39:
	print(s:"Find UAC credits lying round the base and use them to purchase useful provisions at Junction.");
break;

case 40:
	print(s:"Many of the items found around this base are selfexplanatory, but a few require explanation. The Soul Sphere restores your armor and health to maximum. The Berserker increases your attack briefly. These are one-time use items.");
break;

case 41:
	print(s:"You can buy stat boosters at a vending machine computer. These increase your Defense, Agility, Strength, and Accuracy. Defense is your resistance to attacks. Agility is your ability to evade attacks. Strength is the damage you can inflict. Accuracy is your ability to land an attack.");
break;

case 42:
	print(s:"Seems stupid for the UAC to be charging a Marine for combat equipment.");
break;

case 43:
	print(s:"I'm a doctor, relax. I'll dress your wounds.");
break;

case 44:
	print(s:"Health restored.");
break;

case 45:
	print(s:"Feeling better?");
break;

case 46:
	print(s:"Come see me any time you need medical attention.");
break;

case 47:
	print(s:"Use the Medkits in your inventory if you're hurt during combat.");
break;

case 48:
	print(s:"Sorry Marine, this area is off limits. Dr. Guerard ordered a quarantine of the reactor area.");
break;

case 49:
	print(s:"This passage leads to Sector 2. You are welcome to try it out but you should probably try playing through Sector 1 first.");
break;

case 50:
	print(s:"This passage leads to Sector 3. You should consider completing Sector 2 before entering Sector 3. But hey, do whatever you want.");
break;

case 51:
	print(s:"Don't know why but my colleagues, Dr. Jensen and Dr. Guerard, have it out for each other. I don't trust either of them!");
break;

case 52:
	print(s:"I heard Dr. Guerard got Dr. Jensen fired. Not sure I believe that though. I think Jensen was just sloppy with his security procedures.");
break;

case 53:
	print(s:"Kronos is going to kill us all!");
break;

case 54:
	print(s:"Rumor is that Jensen was fired for security breaches but Guerard may have had something to do with it.");
break;

case 55:
	print(s:"Have you met Kronos? I've been here for years but have never met him.");
break;

case 56:
	print(s:"Lots of equipment has disappeared. Hope it turns up intact.");
break;

case 57:
	print(s:"The scientists at this facility are insane!");
break;

case 58:
	print(s:"Oh, you have the blue keycard? Jensen had it when we arrested him. Hope Guerard doesn't come looking for it.");
break;

case 59:
	print(s:"Someone told me they saw Guerard transform into some kind of horrible creature. I wonder what that is all about.");
break;

case 60:
	print(s:"I don't know who to trust anymore.");
break;

case 61:
	print(s:"I won't tell anyone you have the card. I don't trust Guerard. I'd rather you have it than him.");
break;

case 62:
	print(s:"I'm beginning to wonder if anyone will make it out of here alive.");
break;

case 63:
	print(s:"I was working in Sector 5 as part of the unit that arrested Dr. Jensen. I remember he was fired several weeks ago so I'm not sure why he's still at this facility.");
break;

case 64:
	print(s:"I need to get into the green zone but I misplaced my green keycard.");
break;

case 65:
	print(s:"You found my green keycard! Keep it. You need it more than I do.");
break;

case 66:
	print(s:"I'm freaked. I have a feeling something really bad is about to happen.");
break;

case 67:
	print(s:"Guerard went down to the reactor. I hope he can put an end to this invasion!");
break;

case 68:
	print(s:"I think I left my green keycard in Sector 3, in the yellow zone.");
break;

case 69:
	print(s:"Good luck, Marine.");
break;

case 70:
	print(s:"I can't get through the green door without my green keycard.");
break;

case 71:
	print(s:"You have yellow security clearance. Proceed through the yellow door.");
break;

case 72:
	print(s:"I worked with Guerard and Jensen on the teleportation research team. Those two really have it out for each other.");
break;

case 73:
	print(s:"My feet hurt from standing here so long.");
break;

case 74:
	print(s:"I have a really bad feeling about Guerard. Between us, I think he is the one responsible for this mess.");
break;

case 75:
	print(s:"Search the base for additional colored keycards which allow access to more areas in Junction.");
break;

case 76:
	print(s:"Jensen got fired over a security matter. Rumor is that Guerard got him fired though Jensen did nothing wrong. I don't believe it. Dr. Guerard was an outstanding employee, putting in extra hours at night and befriending UAC administrators. He's a nice guy.");
break;

case 77:
	print(s:"The red keycard is the highest level of security clearance - it allows access to the reactor area which houses the power plant providing energy to the entire facility.");
break;

case 78:
	print(s:"I heard Jensen is still on base investigating his firing. Hope he uncovers the truth.");
break;

case 79:
	print(s:"These doors lead to various areas of the base. In each subsequent sector the journey gets harder. Since the more you fight the stronger you get, stick to the easy areas first.");
break;

case 80:
	print(s:"Seems you've cleared Sector 3 and acquired a green keycard. Continue your mission by heading to the green zone and clearing Sectors 4 and 5.");
break;

case 81:
	print(s:"We won't make it much longer. It's only a matter of time before the monsters enter Junction.");
break;

case 82:
	print(s:"I heard Nadira got eaten by a monster. No loss. I never liked the guy.");
break;

case 83:
	print(s:"You will be taken back to Junction should you get incapacitated during combat.");
break;

case 84:
	print(s:"Not sure how long we'll last here at Junction. Monsters have taken over every other part of the base and we need supplies.");
break;

case 85:
	print(s:"You can replay a sector several times to build up your abilities.");
break;

case 86:
	print(s:"Good to see you made it. Your current objective is to seek information on the cause of this invasion and find a way to stop it.");
break;

case 87:
	print(s:"I don't trust Guerard and I don't think you should either. I've heard that he's working with Kronos and that they're responsible for this mess.");
break;

case 88:
	print(s:"It's only a matter of time before the demons overrun the entire planet...");
break;

case 89:
	print(s:"What? The main reactor is back online? I hope they aren't planning on reopening the portal.");
break;

case 90:
	print(s:"You'll need additional colored keycards to gain access to all the areas accessible from Junction.");
break;

case 91:
	print(s:"Trust your instincts. It's the only way to survive.");
break;

case 92:
	print(s:"Bioscans indicate the monsters are coming from the underground reactor sector. Strange... how could they be invading from a geothermic reactor deep inside a Martian cavern?");
break;

case 93:
	print(s:"You know what to expect: more sector doors to explore in the hunt for the next colored keycard. Get to it!");
break;

case 94:
	print(s:"A lot of the scientists look EXACTLY like me. Why you may ask? Is this outpost some cloning facility or are the game designers too lazy to create a variety of characters? Or is it something more insidious, like extremely small memory constraints for portable devices that won't allow much graphical variety?!");
break;

case 95:
	print(s:"Have you noticed that if you keep talking to people here they make trite inside jokes and other misguided attempts at humor?");
break;

case 96:
	print(s:"Ever hear of Kronos? He was a UAC scientist working on teleportation research years ago. It's said that he traveled from our dimension to one of pure evil where he fused human technology with demonic flesh, creating a new super weapon. UAC fired Kronos and buried the research but rumor has it that Kronos is on this base trying to bring his creation into our dimension.");
break;

case 97:
	print(s:"If you come across him, stop him. Be careful, Kronos is controlling the minds of UAC administrators.");
break;

case 98:
	print(s:"I think Kronos moved the teleportation research equipment into the reactor core and plans to use the massive of the reactor core to move something very large into our dimension.");
break;

case 99:
	print(s:"Hey, by the way, you didn't hear any of this from me, OK?");
break;

case 100:
	print(s:"The Union Aerospace Corporation welcomes you to Junction. Here you have access to clean, quiet living conditions with all the latest amenities, such as combat equipment vending and medical facilities. Think of Junction as your home away from home.");
break;

case 101:
	print(s:"The UAC strives to be a safe and friendly work environment.");
break;

case 102:
	print(s:"[Email] From: J. Raphael To: M. Ross Matt, I've been transferred to a unit in charge of moving a bunch of machinery from the labs to the reactor sector. Not sure what that's all about but I won't be able to make our DDR party tonight. I have to work overtime. TTYL. -Jah");
break;

case 103:
	print(s:"[Email] From: J. Raphael To: M. Ross Dude, the invasion happened a day after all the stuff from the labs were moved to the reactor sector. Not sure what's going on but I think Guerard may have had a hand in this. Heard that Guerard ordered the move. -Jah");
break;

case 104:
	print(s:"Segment Fault: G_3R4%D 15 K&0N^5");
break;

case 105:
	print(s:"System offline.");
break;

case 106:
	print(s:"[Email] From: M. Ross To: J. Raphael Man, lots of weird things are going on. I've been working crazy hours at the machine shop but nobody tells me what I'm working on. I have a strange feeling it has to do with what's going on at the reactor. -Matt");
break;

case 107:
	print(s:"No more email.");
break;

case 108:
	print(s:"[Email] From: Col. Graff To: D. Whitlark Whitlark, where are the reports you promised me? You said they'd be done by Tuesday! -Col. Graff");
break;

case 109:
	print(s:"INCOMING TEXT MESSAGE: HELP! I'm being held against my will in Sector 5. They've taken my blue keycard and weapon! I have my cell phone but the battery is about to die and this is the last text message I'll be able to send. Someone please help me! -Dr. Jensen");
break;

case 110:
	print(s:"[Email] From: D. Whitlark To: Col. Graff Sorry sir. I was a little distracted. I discovered an old computer game called DOOM... it has to be at least 100 years old but it's still surprisingly addictive. The weird thing is that the setting and scenario of the game is similar to ours. Funny, eh? -David");
break;

case 111:
	print(s:"[Email] From: Col. Graff To: D. Whitlark Just get me the damned reports! -Col. Graff");
break;

case 112:
	print(s:"[Email] From: D. Whitlark To: Col. Graff Yes sir! You'll have them today. BTW, they're making DOOM for the cell phone. Cool, eh? -David");
break;

case 113:
	print(s:"Log Entry of Dr. Jensen: *CLASSIFIED* Our budget has been increased to fund the study of matter transportation. We hope to have a functional prototype ready for demonstration in a few months.");
break;

case 114:
	print(s:"Log Entry of Dr. Guerard: *CLASSIFIED* Seems that my colleague, Dr. Jensen, has been fired over some petty security matters. It's unfortunate; he was a skilled scientist.");
break;

case 115:
	print(s:"[Email] To: B. Smith From: K. Simons Dr. Jensen had me investigate Dr. Guerard's employment history. What I found was strange. Guerard was supposedly hired onto the teleportation research team 2 years ago but UACHQ has no record of him. -Karina");
break;

case 116:
	print(s:"Log Entry of Dr. Jensen: *CLASSIFIED* Dr. Guerard says the electrical requirements of our device exceeded his initial estimations. We will likely have to move the device to a location with a larger energy source.");
break;

case 117:
	print(s:"Log Entry of Dr. Guerard: *CLASSIFIED* With Mr. Nadira's assistance, I was able to convince Col. Graff to move our equipment from the lab to the reactor. This move should help meet the energy demands of our next set of experiments.");
break;

case 118:
	print(s:"[Email] To: K. Simons From: B. Smith Well, the UAC is a huge bureaucracy with billions of records. They're bound to lose one once in a while. -Brett");
break;

case 119:
	print(s:"Log Entry of Dr. Jensen: *CLASSIFIED* This is my last log update. I've been fired for supposed "breaches" in security protocol and somehow my research documents were compromised. I have no idea how this happened but I intend to find out.");
break;

case 120:
	print(s:"End of log.");
break;

case 121:
	print(s:"[Combat Guide] Tip 133: A is for Axe; crashes like thunder. Z is for zombies, rend them asunder.");
break;

case 122:
	print(s:"[Combat Guide] Tip 147: Reports have come in that the Commando class is weak against plasma.");
break;

case 123:
	print(s:"[Combat Guide] Tip 161: The Mancubus class will blast you with rockets; he doesn't like the taste of his own medicine.");
break;

case 124:
	print(s:"[Combat Guide] Tip 134: B is for buckshot, tried and true. Canines, Imps and Barons hate you.");
break;

case 125:
	print(s:"[Combat Guide] Tip 148: Fire retardant has proven effective against fire creatures. Imagine that!");
break;

case 126:
	print(s:"[Combat Guide] Tip 162: Those damn bull demon things aren't as affected by rockets as you'd think.");
break;

case 127:
	print(s:"");
break;
