
case 0:
	print(s:"Junction");
break;

case 1:
	print(s:"/junction.bsp");
break;

case 2:
	print(s:"/reactor.bsp");
break;

case 3:
	print(s:"Enter Reactor");
break;

case 4:
	print(s:"");
break;

case 5:
	print(s:"West wing");
break;

case 6:
	print(s:"Central corridor");
break;

case 7:
	print(s:"East wing");
break;

case 8:
	print(s:"North wing");
break;

case 9:
	print(s:"Junction");
break;

case 10:
	print(s:"Locked Door");
break;

case 11:
	print(s:"Thank god you're back! We've suffered a massive attack! Hordes of monsters swarmed into Junction from the reactor area.");
break;

case 12:
	print(s:"Go to red zone and talk to Dr. Kelvin.");
break;

case 13:
	print(s:"Dr. Kelvin was able to seal up the door to the reactor to stop the attack. Hope he's OK... get down to the reactor entrance in the red zone and see if you can help him.");
break;

case 14:
	print(s:"Ugh, I don't feel so good...");
break;

case 15:
	print(s:"Oh no...");
break;

case 16:
	print(s:"Find Jensen. Last seen in north wing.");
break;

case 17:
	print(s:"[Dr. Kelvin] Marine! I'm so glad to see you! It's been hell down here. I was able to lock this door to stop the invasion but I'm not sure what to do now. Find Dr. Jensen and see how we should proceed... he was in the north wing last time I saw him.");
break;

case 18:
	print(s:"[Dr. Kelvin] What the hell was that? I hope Dr. Jensen is OK. Go find him.");
break;

case 19:
	print(s:"[Dr. Kelvin] Go check in with Dr. Jensen. He is probably still in the north wing.");
break;

case 20:
	print(s:"Use passcode 5966 to enter the reactor area.");
break;

case 21:
	print(s:"[Dr. Kelvin] What? Jensen's dead?! You have to end this or we'll all die. Go in there, the passcode is 5966. Godspeed.");
break;

case 22:
	print(s:"[Dr. Kelvin] 5966 will open the door.");
break;

case 23:
	print(s:"[Dr. Kelvin] Ugh. One of those things got inside me. I can feel it. Help me!");
break;

case 24:
	print(s:"[Dr. Kelvin] That computer terminal controls the door that leads to the reactor core. Don't mess with it.");
break;

case 25:
	print(s:"[Dr. Kelvin] We don't want that door opening again.");
break;

case 26:
	print(s:"[Dr. Kelvin] Whose side are you on? Leave that terminal alone!");
break;

case 27:
	print(s:"5966");
break;

case 28:
	print(s:"Door locked. Enter code:");
break;

case 29:
	print(s:"Door opened.");
break;

case 30:
	print(s:"[Dr. Kelvin] Watch out! Here they come!");
break;

case 31:
	print(s:"Dr. Kelvin is down at the reactor door entrance in the red zone. He wanted to talk with you.");
break;

case 32:
	print(s:"I'm guarding this position to prevent any more monsters from getting into Junction.");
break;

case 33:
	print(s:"The entrance to the north wing just collapsed! Dr. Jensen was in there. I hope he's- uh, what is happening to me? Ahhhhh!");
break;

case 34:
	print(s:"I'm so scared...");
break;

case 35:
	print(s:"We're all gonna die! Don't you get it?! We have to get out of here!");
break;

case 36:
	print(s:"I feel a tingling sensation. What is going on? Ahhhhh!");
break;

case 37:
	print(s:"Look at the carnage! I don't think anyone made it out alive!");
break;

case 38:
	print(s:"I'm too late to help any of these people, but let me at least help you...");
break;

case 39:
	print(s:"Health restored.");
break;

case 40:
	print(s:"Good luck, Marine.");
break;

case 41:
	print(s:"I'm knee-deep in the dead.");
break;

case 42:
	print(s:"What? The passage to the north wing is blocked? You'll probably just have to find another way in.");
break;

case 43:
	print(s:"Sorry. I don't have any more Medkits. I used my last one on you.");
break;

case 44:
	print(s:"Please! Don't let them hurt me!");
break;

case 45:
	print(s:"They are coming for us.");
break;

case 46:
	print(s:"I'm hit!");
break;

case 47:
	print(s:"Argh! Damn it!");
break;

case 48:
	print(s:"[Dr. Jensen] Marine, How'd you get in here? I thought this room was cut off from Junction when the ceiling caved in. I'm OK, but I have bad news...");
break;

case 49:
	print(s:"[Dr. Jensen] Guerard reopened the portal. He brought the reactor back online to reopen the link with Hell. According to what I've found, Dr. Guerard intends to bring Kronos's creation, the Cyberdemon, into our dimension...");
break;

case 50:
	print(s:"Head down to the reactor area in the red zone.");
break;

case 51:
	print(s:"We must make every effort to prevent this from happening. Have Dr. Kelvin open the door to the reactor. Head down there and destroy the portal. You are our only hope.");
break;

case 52:
	print(s:"Uh oh.");
break;

case 53:
	print(s:"Goodbye, Marine.");
break;

case 54:
	print(s:"I'm going to kill you... slowly. -Kronos");
break;

case 55:
	print(s:"System offline.");
break;

case 56:
	print(s:"I have plans for you, Marine. Meet me at the reactor. -Kronos");
break;

case 57:
	print(s:"They stopped me years ago but they can't stop me this time. -Kronos");
break;

case 58:
	print(s:"0112358");
break;

case 59:
	print(s:"[Bonus Area!] Door locked. Enter code:");
break;

case 60:
	print(s:" Door unlocked.");
break;

case 61:
	print(s:"");
break;
